name: Build, Push, and Deploy to ECS
 
on:
  push:
    branches:
      - main # Trigger the workflow when pushing to the main branch
 
env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: stage-ecs-cluster
  NGINX_SERVICE: stage-nginx-service
  TOMCAT_SERVICE: stage-tomcat-service
  APACHE_SERVICE: stage-apache-service
  ECR_REGISTRY: public.ecr.aws/s2z0q2f0
  ECR_NGINX_REPO: nginx
  ECR_TOMCAT_REPO: tomcat
  ECR_APACHE_REPO: apache

permissions:
  id-token: write
  contents: read
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1
 
      # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s2z0q2f0
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
 
    
 
    - name: Build and Push NGINX Docker image
      run: |
        docker build -t nginx .
        docker tag nginx:latest $ECR_REGISTRY/$ECR_NGINX_REPO:latest
        docker push $ECR_REGISTRY/$ECR_NGINX_REPO:latest
 
    - name: Build and Push Tomcat Docker image
      run: |
        docker build -t tomcat .
        docker tag tomcat:latest $ECR_REGISTRY/$ECR_TOMCAT_REPO:latest
        docker push $ECR_REGISTRY/$ECR_TOMCAT_REPO:latest
 
    - name: Build and Push Apache Docker image
      run: |
        docker build -t apache .
        docker tag apache:latest $ECR_REGISTRY/$ECR_APACHE_REPO:latest
        docker push $ECR_REGISTRY/$ECR_APACHE_REPO:latest
 
    - name: Fetch Latest Task Definition Revision for NGINX
      id: nginx-task
      run: |
        TASK_DEFINITION_REVISION=$(aws ecs describe-task-definition --task-definition $ECR_NGINX_REPO | jq -r '.taskDefinition.revision')
        echo "NGINX_TASK_DEFINITION=$TASK_DEFINITION_REVISION" >> $GITHUB_ENV
 
    - name: Fetch Latest Task Definition Revision for Tomcat
      id: tomcat-task
      run: |
        TASK_DEFINITION_REVISION=$(aws ecs describe-task-definition --task-definition $ECR_TOMCAT_REPO | jq -r '.taskDefinition.revision')
        echo "TOMCAT_TASK_DEFINITION=$TASK_DEFINITION_REVISION" >> $GITHUB_ENV
 
    - name: Fetch Latest Task Definition Revision for Apache
      id: apache-task
      run: |
        TASK_DEFINITION_REVISION=$(aws ecs describe-task-definition --task-definition $ECR_APACHE_REPO | jq -r '.taskDefinition.revision')
        echo "APACHE_TASK_DEFINITION=$TASK_DEFINITION_REVISION" >> $GITHUB_ENV
 
    - name: Update NGINX ECS Service
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME --service $NGINX_SERVICE --force-new-deployment --task-definition $ECR_NGINX_REPO:$NGINX_TASK_DEFINITION
 
    - name: Update Tomcat ECS Service
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME --service $TOMCAT_SERVICE --force-new-deployment --task-definition $ECR_TOMCAT_REPO:$TOMCAT_TASK_DEFINITION
 
    - name: Update Apache ECS Service
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME --service $APACHE_SERVICE --force-new-deployment --task-definition $ECR_APACHE_REPO:$APACHE_TASK_DEFINITION
